-- AlterTable
ALTER TABLE "plano_contas" ALTER COLUMN "DESC_NIVEL1" DROP NOT NULL,
ALTER COLUMN "DESC_NIVEL1" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "DESC_NIVEL2" DROP NOT NULL,
ALTER COLUMN "DESC_NIVEL2" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "DESC_NIVEL3" DROP NOT NULL,
ALTER COLUMN "DESC_NIVEL3" SET DATA TYPE VARCHAR(100);
